name: pass-indexer Continuous Integration
on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  run-tests:
    name: "Run Unit & Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2

      - name: "Docker pull"
        run: docker-compose pull

      - name: "Start containers"
        run: docker-compose up -d

      - name: "Wait till ES is ready"
        run: bash .wait.sh

      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Cache Maven packages"
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2          
      - name: "Run unit and integration tests"
        run: mvn -V -ntp verify --file pom.xml

      - name: "Stop containers"
        if: always()
        run: docker-compose -f "docker-compose.yml" down
